baseURL = "https://www.ochrance.cz"
defaultContentLanguage = "cs"
languageCode = "cs"
title = "Obudsman"
relativeurls = true

[outputs]
home = ["HTML", "RSS", "Elastic", "htaccess"]

[taxonomies]
  vystup = "vystupy"
  situation = "situations"


[languages]
  [languages.cs]
    contentDir = "content"
    languageName = "Česky"
    title = "Ombudsman"
    weight = 2
    [languages.cs.params]
    description = "veřejný ochránce práv"
  [languages.en]
    contentDir = "content-en"
    languageName = "English"
    title = "Ombudsman"
    weight = 1
    [languages.en.params]
    description = ""

[markup.goldmark.renderer]
  unsafe = true
  hardWraps = true

[permalinks]
info = "/:filename"

[outputFormats.Elastic]
baseName = "elastic"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.Elastic]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"]

[outputFormats.htaccess]
baseName = ""
isPlainText = true
mediaType = "text/htaccess"

[mediaTypes]
[mediaTypes."text/htaccess"]
suffixes = ["htaccess"]
