[build]
  publish = "public"
  command = "hugo --config preview-netlify.toml"

[context.production.environment]
  HUGO_VERSION = "0.107.0"

[[redirects]]
  from = "/*"
  to = "/err/404/"
  status = 404

