[build]
  publish = "public"
  command = "hugo serve --config preview.toml"

[context.production.environment]
  HUGO_VERSION = "0.81.0"

[[redirects]]
  from = "/*"
  to = "/err/404/"
  status = 404

