backend:
  name: git-gateway
  branch: master
media_folder: content/media
public_folder: /media
site_domain: 'http://ochrance-preview.netlify.app'
display_url: 'http://ochrance-preview.netlify.app'
slug:
  encoding: ascii
  clean_accents: true
  sanitize_replacement: _
collections:
  - name: aktualne
    label: Aktuality
    label_singular: aktualita
    folder: content/aktualne
    extension: md
    editor:
      preview: false
    fields:
      - label: Titulek
        name: title
        widget: string
      - label: Datum
        name: date
        required: false
        widget: datetime
        dateFormat: DD.MM.YYYY
        timeFormat: 'HH:mm'
      - label: Perex
        name: perex
        required: false
        widget: markdown
      - label: Text
        name: body
        required: false
        widget: markdown
    create: true
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
  - name: dokument
    label: Dokumenty
    label_singular: dokument
    folder: content/dokument
    extension: md
    editor:
      preview: false
    fields:
      - label: Titulek
        name: title
        widget: string
      - label: Štítky
        name: tags
        required: false
        widget: select
        options:
          - Výroční zpráva
          - Publikace
          - Připomínky k zákonům
          - Materiál pro vládu
          - Newsletter
          - Seriál na ČT
          - Bulletin k monitorování práv lidí s postižením
        multiple: true
      - label: Text
        name: body
        required: false
        widget: markdown
      - label: Přílohy
        name: attachments
        required: false
        label_singular: Příloha
        widget: list
        fields:
          - label: Název přílohy
            name: title
            widget: string
          - label: Soubor
            name: file
            required: false
            widget: file
    create: true
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
