backend:
  name: git-gateway
  branch: main
media_folder: content/media
public_folder: /media
site_domain: 'http://ochrance-preview.netlify.app'
display_url: 'http://ochrance-preview.netlify.app'
slug:
  encoding: ascii
  clean_accents: true
  sanitize_replacement: _
collections:
  - name: stranky
    label: Stránky
    editor:
      preview: false
    files:
      - label: Varování
        name: varovani
        file: content/alert/_index.markdown
        fields: &ref_0
          - label: Titulek
            name: title
            widget: string
          - label: Je varování aktivní?
            name: active
            required: false
            widget: boolean
          - label: Podrobný popis
            name: body
            required: false
            hint: >-
              Titulek se zobrazí na titulní straně, detailní popis na samostatné
              stránce.
            widget: markdown
      - label: Zpracování osobních údajů
        name: ou
        file: content/info/zpracovani-ou.md
        fields: &ref_1
          - label: Titulek
            name: title
            widget: string
          - label: Popis
            name: body
            required: false
            widget: markdown
  - name: aktualne
    label: Aktuality
    label_singular: aktualita
    folder: content/aktualne
    extension: md
    editor: &ref_2
      preview: false
    fields: &ref_3
      - label: Titulek
        name: title
        widget: string
      - label: Datum
        name: date
        required: false
        widget: datetime
        date_format: DD.MM.YYYY
        time_format: false
      - label: Perex
        name: perex
        required: false
        widget: markdown
      - label: Text
        name: body
        required: false
        widget: markdown
    create: true
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
  - name: dokument
    label: Dokumenty
    label_singular: dokument
    folder: content/dokument
    extension: md
    editor: &ref_4
      preview: false
    fields: &ref_5
      - label: Titulek
        name: title
        widget: string
      - label: Štítky
        name: tags
        required: false
        widget: select
        options:
          - label: Výroční zpráva
            value: vyrocni-zprava
          - label: Publikace
            value: publikace
          - label: Připomínky k zákonům
            value: pripominky
          - label: Materiál pro vládu
            value: pro-vladu
          - label: Newsletter
            value: newsletter
          - label: Seriál na ČT
            value: ct
          - label: Podcast
            value: podcast
          - label: Bulletin k monitorování práv lidí s postižením
            value: bulletin
        multiple: true
      - label: Text
        name: body
        required: false
        widget: markdown
      - label: Přílohy
        name: attachments
        required: false
        label_singular: Příloha
        widget: list
        fields:
          - label: Název přílohy
            name: title
            widget: string
          - label: Soubor
            name: file
            required: false
            widget: file
    create: true
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
  - name: onas
    label: O nás
    editor:
      preview: false
    files:
      - label: Veřejný ochránce práv
        name: ombudsman
        file: content/o-nas/ombudsman/index.md
        fields: &ref_6
          - label: Název role
            name: title
            widget: string
          - label: Jméno
            name: name
            required: false
            widget: string
          - label: Portrét
            name: pic
            required: false
            widget: image
          - label: Citát / motto
            name: quote
            required: false
            widget: string
          - label: Krátký životopis
            name: bio
            required: false
            widget: markdown
          - label: Oblasti
            name: areas
            required: false
            label_singular: Oblast
            widget: list
            fields:
              - label: Název
                name: area
                required: false
                widget: string
              - label: Popis
                name: desc
                required: false
                widget: string
        media_folder: ''
      - label: Zástupce
        name: deputy
        file: content/o-nas/deputy/index.md
        fields: &ref_7
          - label: Název role
            name: title
            widget: string
          - label: Jméno
            name: name
            required: false
            widget: string
          - label: Portrét
            name: pic
            required: false
            widget: image
          - label: Citát / motto
            name: quote
            required: false
            widget: string
          - label: Krátký životopis
            name: bio
            required: false
            widget: markdown
          - label: Oblasti
            name: areas
            required: false
            label_singular: Oblast
            widget: list
            fields:
              - label: Název
                name: area
                required: false
                widget: string
              - label: Popis
                name: desc
                required: false
                widget: text
        media_folder: ''
      - label: Historie
        name: historie
        file: content/o-nas/historie/index.md
        fields: &ref_8
          - label: Titulek
            name: title
            widget: string
          - label: Časová osa
            name: timeline
            required: false
            label_singular: Událost
            widget: list
            fields:
              - label: Časové určení
                name: time
                required: false
                widget: string
              - label: Popis
                name: desc
                required: false
                widget: text
  - name: pusobnost
    label: Působnost
    label_singular: Oblast
    folder: content/pusobnost
    extension: md
    editor: &ref_9
      preview: false
    fields: &ref_10
      - label: Název oblasti
        name: title
        widget: string
      - label: Barva hlavičky
        name: headerColor
        required: false
        widget: select
        options:
          - label: Zelená
            value: green
          - label: Růžová
            value: pink
          - label: Oranžová
            value: orange
          - label: Žlutozelená
            value: yellow
      - label: Perex
        name: perex
        required: false
        widget: markdown
      - label: Text
        name: body
        required: false
        widget: markdown
      - widget: object
        label: Kontaktní patička
        name: cta
        required: false
        fields:
          - label: Nadpis
            name: title
            widget: string
          - label: Odkaz
            name: btnLink
            required: false
            hint: Výchozí odkaz směřuje na stránku podání stížnosti.
            widget: string
        collapsed: true
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
  - name: potrebuji-pomoc
    label: Potřebuji pomoc
    label_singular: Problematika
    folder: content/potrebuji-pomoc
    extension: md
    editor: &ref_11
      preview: false
    fields: &ref_12
      - label: Titulek
        name: title
        widget: string
      - label: Perex
        name: perex
        required: false
        widget: markdown
      - label: Popisek na homepage
        name: hp
        required: false
        widget: markdown
      - label: Úvodní text
        name: body
        required: false
        widget: markdown
      - label: 'Seznam: můžeme pomoci'
        name: we-can
        required: false
        label_singular: Situace
        widget: list
        field:
          label: Situace
          name: situation
          required: false
          widget: markdown
      - label: 'Seznam: nemůžeme pomoci'
        name: we-cannot
        required: false
        label_singular: Situace
        widget: list
        field:
          label: Situace
          name: situation
          required: false
          widget: markdown
      - label: Příklady
        name: examples
        required: false
        label_singular: Příklad
        widget: list
        fields:
          - label: Jméno
            name: name
            required: false
            widget: string
          - label: Popis případu
            name: desc
            required: false
            widget: markdown
      - widget: object
        label: Sekce „podejte podnět“
        name: button
        required: false
        fields:
          - label: Text na tlačítku
            name: text
            required: false
            widget: string
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
  - label: Stránky (EN)
    name: stranky-en
    files:
      - label: Varování
        name: varovani
        file: content-en/alert/_index.markdown
        fields: *ref_0
      - label: Zpracování osobních údajů
        name: ou
        file: content-en/info/zpracovani-ou.md
        fields: *ref_1
  - name: aktualne-en
    label: Aktuality (EN)
    label_singular: aktualita
    folder: content-en/aktualne
    extension: md
    editor: *ref_2
    fields: *ref_3
    create: true
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
  - name: dokument-en
    label: Dokumenty (EN)
    label_singular: dokument
    folder: content-en/dokument
    extension: md
    editor: *ref_4
    fields: *ref_5
    create: true
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
  - label: O nás (EN)
    name: onas-en
    files:
      - label: Veřejný ochránce práv
        name: ombudsman
        file: content-en/o-nas/ombudsman/index.md
        fields: *ref_6
        media_folder: ''
      - label: Zástupce
        name: deputy
        file: content-en/o-nas/deputy/index.md
        fields: *ref_7
        media_folder: ''
      - label: Historie
        name: historie
        file: content-en/o-nas/historie/index.md
        fields: *ref_8
  - name: pusobnost-en
    label: Působnost (EN)
    label_singular: Oblast
    folder: content-en/pusobnost
    extension: md
    editor: *ref_9
    fields: *ref_10
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
  - name: potrebuji-pomoc-en
    label: Potřebuji pomoc (EN)
    label_singular: Problematika
    folder: content-en/potrebuji-pomoc
    extension: md
    editor: *ref_11
    fields: *ref_12
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
