backend:
  name: git-gateway
  branch: main
media_folder: content/media
public_folder: /media
site_domain: 'http://ochrance-preview.netlify.app'
display_url: 'http://ochrance-preview.netlify.app'
slug:
  encoding: ascii
  clean_accents: true
  sanitize_replacement: _
collections:
  - name: aktualne
    label: Aktuality
    label_singular: aktualita
    folder: content/aktualne
    extension: md
    editor:
      preview: false
    fields:
      - label: Titulek
        name: title
        widget: string
      - label: Datum
        name: date
        required: false
        widget: datetime
        date_format: DD.MM.YYYY
        time_format: false
      - label: Perex
        name: perex
        required: false
        widget: markdown
      - label: Text
        name: body
        required: false
        widget: markdown
    create: true
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
  - name: dokument
    label: Dokumenty
    label_singular: dokument
    folder: content/dokument
    extension: md
    editor:
      preview: false
    fields:
      - label: Titulek
        name: title
        widget: string
      - label: Štítky
        name: tags
        required: false
        widget: select
        options:
          - label: Výroční zpráva
            value: vyrocni-zprava
          - label: Publikace
            value: publikace
          - label: Připomínky k zákonům
            value: pripominky
          - label: Materiál pro vládu
            value: pro-vladu
          - label: Newsletter
            value: newsletter
          - label: Seriál na ČT
            value: ct
          - label: Podcast
            value: podcast
          - label: Bulletin k monitorování práv lidí s postižením
            value: bulletin
        multiple: true
      - label: Text
        name: body
        required: false
        widget: markdown
      - label: Přílohy
        name: attachments
        required: false
        label_singular: Příloha
        widget: list
        fields:
          - label: Název přílohy
            name: title
            widget: string
          - label: Soubor
            name: file
            required: false
            widget: file
    create: true
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
  - name: pusobnost
    label: Působnost
    label_singular: Oblast
    folder: content/pusobnost
    extension: md
    editor:
      preview: false
    fields:
      - label: Název oblasti
        name: title
        widget: string
      - label: Barva hlavičky
        name: headerColor
        required: false
        widget: select
        options:
          - label: Zelená
            value: green
          - label: Růžová
            value: pink
          - label: Oranžová
            value: orange
      - label: Perex
        name: perex
        required: false
        widget: markdown
      - label: Text
        name: body
        required: false
        widget: markdown
      - widget: object
        label: Kontaktní patička
        name: cta
        required: false
        fields:
          - label: Nadpis
            name: title
            widget: string
          - label: Odkaz
            name: btnLink
            required: false
            hint: Výchozí odkaz směřuje na stránku podání stížnosti.
            widget: string
        collapsed: true
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
