backend:
  name: git-gateway
  branch: main
media_folder: content/media
public_folder: /media
site_domain: 'http://ochrance-preview.netlify.app'
display_url: 'http://ochrance-preview.netlify.app'
slug:
  encoding: ascii
  clean_accents: true
  sanitize_replacement: _
collections:
  - name: stranky
    label: Stránky
    editor:
      preview: false
    files:
      - label: Homepage
        name: home
        file: content/_index.markdown
        fields: &ref_0
          - label: Titulek
            name: title
            widget: string
          - label: Motto
            name: claim
            required: false
            widget: string
          - label: Hlavní text
            name: body
            required: false
            widget: markdown
          - label: 'Mezititulek: potřebuji pomoc'
            name: situationsTitle
            required: false
            widget: string
          - label: 'Mezititulek: činnost'
            name: cinnostTitle
            required: false
            widget: string
          - label: Info o přístupnosti
            name: accessibility
            required: false
            widget: markdown
          - label: Souhlas u newsletteru
            name: consent
            required: false
            widget: markdown
      - label: Varování
        name: varovani
        file: content/alert/_index.markdown
        fields: &ref_1
          - label: Titulek
            name: title
            widget: string
          - label: Je varování aktivní?
            name: active
            required: false
            widget: boolean
          - label: Podrobný popis
            name: body
            required: false
            hint: >-
              Titulek se zobrazí na titulní straně, detailní popis na samostatné
              stránce.
            widget: markdown
      - label: Kontakt
        name: ou
        file: content/kontakt.md
        fields: &ref_2
          - label: Titulek
            name: title
            widget: string
          - label: Podtitul
            name: description
            required: false
            widget: string
          - label: Titulek v menu
            name: menuTitle
            required: false
            widget: string
          - label: Telefonní číslo
            name: phone
            required: false
            widget: string
          - label: E-mail
            name: email
            required: false
            widget: string
          - label: ID datové schránky
            name: dataId
            required: false
            widget: string
          - label: Adresa
            name: address
            required: false
            widget: markdown
          - label: Komentář k adrese
            name: addressComment
            required: false
            widget: string
          - label: Popis infolinky s online-přepisem
            name: infolineHearing
            required: false
            widget: markdown
          - widget: object
            label: Přístup do budov
            name: access
            required: false
            fields:
              - label: Pěšky
                name: walk
                required: false
                widget: markdown
              - label: MHD
                name: public
                required: false
                widget: markdown
              - label: Obecně
                name: universal
                required: false
                widget: markdown
              - label: Ilustrační obrázek
                name: pic
                required: false
                widget: image
  - name: aktualne
    label: Aktuality
    label_singular: aktualita
    folder: content/aktualne
    extension: md
    editor: &ref_3
      preview: false
    fields: &ref_4
      - label: Titulek
        name: title
        widget: string
      - label: Datum
        name: date
        required: false
        widget: datetime
        date_format: DD.MM.YYYY
        time_format: false
      - label: Perex
        name: perex
        required: false
        widget: markdown
      - label: Text
        name: body
        required: false
        widget: markdown
    create: true
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
  - name: dokument
    label: Dokumenty
    label_singular: dokument
    folder: content/dokument
    extension: md
    editor: &ref_5
      preview: false
    fields: &ref_6
      - label: Titulek
        name: title
        widget: string
      - label: Štítky
        name: tags
        required: false
        widget: select
        options:
          - label: Výroční zpráva
            value: vyrocni-zprava
          - label: Publikace
            value: publikace
          - label: Připomínky k zákonům
            value: pripominky
          - label: Materiál pro vládu
            value: pro-vladu
          - label: Newsletter
            value: newsletter
          - label: Seriál na ČT
            value: ct
          - label: Podcast
            value: podcast
          - label: Bulletin k monitorování práv lidí s postižením
            value: bulletin
        multiple: true
      - label: Text
        name: body
        required: false
        widget: markdown
      - label: Přílohy
        name: attachments
        required: false
        label_singular: Příloha
        widget: list
        fields:
          - label: Název přílohy
            name: title
            widget: string
          - label: Soubor
            name: file
            required: false
            widget: file
    create: true
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
  - name: onas
    label: O nás
    editor:
      preview: false
    files:
      - label: O kanceláři
        name: o-kancelari
        file: content/o-nas/_index.markdown
        fields: &ref_7
          - label: Titulek stránky
            name: title
            widget: string
          - label: Titulek v menu
            name: menuTitle
            required: false
            widget: string
          - label: Perex
            name: description
            required: false
            widget: markdown
          - label: Text stránky
            name: body
            required: false
            widget: markdown
          - label: Odkazy
            name: links
            required: false
            label_singular: Odkaz
            widget: list
            fields:
              - label: Odkaz
                name: link
                required: false
                widget: string
              - label: Popis
                name: text
                required: false
                widget: string
      - label: Veřejný ochránce práv
        name: ombudsman
        file: content/o-nas/ombudsman/index.md
        fields: &ref_8
          - label: Název role
            name: title
            widget: string
          - label: Jméno
            name: name
            required: false
            widget: string
          - label: Portrét
            name: pic
            required: false
            widget: image
          - label: Citát / motto
            name: quote
            required: false
            widget: string
          - label: Krátký životopis
            name: bio
            required: false
            widget: markdown
          - label: Oblasti
            name: areas
            required: false
            label_singular: Oblast
            widget: list
            fields:
              - label: Název
                name: area
                required: false
                widget: string
              - label: Popis
                name: desc
                required: false
                widget: string
        media_folder: ''
      - label: Zástupce
        name: deputy
        file: content/o-nas/deputy/index.md
        fields: &ref_9
          - label: Název role
            name: title
            widget: string
          - label: Jméno
            name: name
            required: false
            widget: string
          - label: Portrét
            name: pic
            required: false
            widget: image
          - label: Citát / motto
            name: quote
            required: false
            widget: string
          - label: Krátký životopis
            name: bio
            required: false
            widget: markdown
          - label: Oblasti
            name: areas
            required: false
            label_singular: Oblast
            widget: list
            fields:
              - label: Název
                name: area
                required: false
                widget: string
              - label: Popis
                name: desc
                required: false
                widget: text
        media_folder: ''
      - label: Historie
        name: historie
        file: content/o-nas/historie/index.md
        fields: &ref_10
          - label: Titulek
            name: title
            widget: string
          - label: Časová osa
            name: timeline
            required: false
            label_singular: Událost
            widget: list
            fields:
              - label: Časové určení
                name: time
                required: false
                widget: string
              - label: Popis
                name: desc
                required: false
                widget: text
      - label: Předpisy
        name: predpisy
        file: content/o-nas/predpisy/index.md
        fields: &ref_11
          - label: Titulek
            name: title
            widget: string
          - label: Text stránky
            name: body
            required: false
            widget: markdown
  - name: pusobnost
    label: Působnost
    label_singular: Oblast
    folder: content/pusobnost
    extension: md
    editor: &ref_12
      preview: false
    fields: &ref_13
      - label: Název oblasti
        name: title
        widget: string
      - label: Barva hlavičky
        name: headerColor
        required: false
        widget: select
        options:
          - label: Zelená
            value: green
          - label: Růžová
            value: pink
          - label: Oranžová
            value: orange
          - label: Žlutozelená
            value: yellow
      - label: Perex
        name: perex
        required: false
        widget: markdown
      - label: Text
        name: body
        required: false
        widget: markdown
      - widget: object
        label: Kontaktní patička
        name: cta
        required: false
        fields:
          - label: Nadpis
            name: title
            widget: string
          - label: Odkaz
            name: btnLink
            required: false
            hint: Výchozí odkaz směřuje na stránku podání stížnosti.
            widget: string
        collapsed: true
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
  - name: potrebuji-pomoc
    label: Potřebuji pomoc
    label_singular: Problematika
    folder: content/potrebuji-pomoc
    extension: md
    editor: &ref_14
      preview: false
    fields: &ref_15
      - label: Titulek
        name: title
        widget: string
      - label: Perex
        name: perex
        required: false
        widget: markdown
      - label: Popisek na homepage
        name: hp
        required: false
        widget: markdown
      - label: Úvodní text
        name: body
        required: false
        widget: markdown
      - label: 'Seznam: můžeme pomoci'
        name: we-can
        required: false
        label_singular: Situace
        widget: list
        field:
          label: Situace
          name: situation
          required: false
          widget: markdown
      - label: 'Seznam: nemůžeme pomoci'
        name: we-cannot
        required: false
        label_singular: Situace
        widget: list
        field:
          label: Situace
          name: situation
          required: false
          widget: markdown
      - label: Příklady
        name: examples
        required: false
        label_singular: Příklad
        widget: list
        fields:
          - label: Jméno
            name: name
            required: false
            widget: string
          - label: Popis případu
            name: desc
            required: false
            widget: markdown
      - widget: object
        label: Sekce „podejte podnět“
        name: button
        required: false
        fields:
          - label: Text na tlačítku
            name: text
            required: false
            widget: string
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
  - name: provoz
    label: Provoz
    label_singular: informační stránka
    folder: content/provoz
    extension: md
    editor: &ref_16
      preview: false
    fields: &ref_17
      - label: Titulek
        name: title
        widget: string
      - label: Text
        name: body
        required: false
        widget: markdown
    create: true
    path: '{{slug}}'
  - name: info
    label: Další informace
    label_singular: informační stránka
    folder: content/info
    extension: md
    editor: &ref_18
      preview: false
    fields: &ref_19
      - label: Titulek
        name: title
        widget: string
      - label: Text
        name: body
        required: false
        widget: markdown
    create: true
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
  - label: Stránky (EN)
    name: stranky-en
    files:
      - label: Homepage
        name: home
        file: content-en/_index.markdown
        fields: *ref_0
      - label: Varování
        name: varovani
        file: content-en/alert/_index.markdown
        fields: *ref_1
      - label: Kontakt
        name: ou
        file: content-en/kontakt.md
        fields: *ref_2
  - name: aktualne-en
    label: Aktuality (EN)
    label_singular: aktualita
    folder: content-en/aktualne
    extension: md
    editor: *ref_3
    fields: *ref_4
    create: true
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
  - name: dokument-en
    label: Dokumenty (EN)
    label_singular: dokument
    folder: content-en/dokument
    extension: md
    editor: *ref_5
    fields: *ref_6
    create: true
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
  - label: O nás (EN)
    name: onas-en
    files:
      - label: O kanceláři
        name: o-kancelari
        file: content-en/o-nas/_index.markdown
        fields: *ref_7
      - label: Veřejný ochránce práv
        name: ombudsman
        file: content-en/o-nas/ombudsman/index.md
        fields: *ref_8
        media_folder: ''
      - label: Zástupce
        name: deputy
        file: content-en/o-nas/deputy/index.md
        fields: *ref_9
        media_folder: ''
      - label: Historie
        name: historie
        file: content-en/o-nas/historie/index.md
        fields: *ref_10
      - label: Předpisy
        name: predpisy
        file: content-en/o-nas/predpisy/index.md
        fields: *ref_11
  - name: pusobnost-en
    label: Působnost (EN)
    label_singular: Oblast
    folder: content-en/pusobnost
    extension: md
    editor: *ref_12
    fields: *ref_13
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
  - name: potrebuji-pomoc-en
    label: Potřebuji pomoc (EN)
    label_singular: Problematika
    folder: content-en/potrebuji-pomoc
    extension: md
    editor: *ref_14
    fields: *ref_15
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
  - name: provoz-en
    label: Provoz (EN)
    label_singular: informační stránka
    folder: content-en/provoz
    extension: md
    editor: *ref_16
    fields: *ref_17
    create: true
    path: '{{slug}}'
  - name: info-en
    label: Další informace (EN)
    label_singular: informační stránka
    folder: content-en/info
    extension: md
    editor: *ref_18
    fields: *ref_19
    create: true
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
