name: deploy to production

on:
  workflow_dispatch:
#  push:
#    branches:
#      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.72.0"
          extended: true

      - name: Build
        run: hugo

      - name: Compress build
        run: tar -zcf build.tar.gz ./public

      - name: Publish
        uses: nogsantos/scp-deploy@master
        with:
          src: ./build.tar.gz
          host: ${{ secrets.SSH_HOSTNAME }}
          remote: /home/ochrance/public_html
          port: ${{ secrets.SSH_PORT }}
          user: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Unpack tar into place
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd /home/ochrance/public_html
            tar -xf build.tar.gz -C ./test --strip-components=2
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
