name: Full update to production

concurrency:
  group: production
  cancel-in-progress: true

env:
  NAME: full-${{ github.run_number }}
  DEST: /home/ochrance/public_html/www-prod

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1-5'

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Upload')"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.125.1'
          extended: true

      - name: Build
        run: hugo

      - name: Write file hashes for partial updates
        run: find public -type f -exec sha256sum {} + | sort > current-hashes.txt

      - name: Cache file hashes for partial updates
        uses: actions/cache/save@v4
        with:
          path: current-hashes.txt
          key: file-hashes-${{ github.run_id }}

      - name: Compress build
        run: |
          tar -zcf ${{ env.NAME }}.tar.gz ./public
          ls -l ${{ env.NAME }}.tar.gz

      - name: Publish
        uses: nogsantos/scp-deploy@master
        with:
          src: ./${{ env.NAME }}.tar.gz
          remote: /home/ochrance/tmp
          host: ${{ secrets.SSH_HOSTNAME }}
          port: ${{ secrets.SSH_PORT }}
          user: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Unpack tar into place
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ochrance/tmp
            echo ${{ github.run_number }} > DEPLOY-RUN-NUMBER.txt
            mkdir -p ${{ env.NAME }}/build

            cd ${{ env.NAME }}
            tar -xf ../${{ env.NAME }}.tar.gz -C ./build --strip-components=2

            if [[ $(<../DEPLOY-RUN-NUMBER.txt) > ${{ github.run_number }} ]]; then
              echo "Newer Github workflow detected. Aborting directory overwrite."
            else
              mv ${{ env.DEST }} old
              mv build ${{ env.DEST }}
            fi

            cd ..
            rm -rf ${{ env.NAME }}
            rm ${{ env.NAME }}.tar.gz

      - name: Update search indices
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.ELASTICUSER_HOSTNAME }}
          username: ${{ secrets.ELASTICUSER_USERNAME }}
          key: ${{ secrets.ELASTICUSER_PRIVATE_KEY }}
          script: |
            wget -O index-${{ github.run_number }}.json http://www.ochrance.cz/elastic.json
            wget -O index-en-${{ github.run_number }}.json http://www.ochrance.cz/en/elastic.json
            curl -X DELETE 'http://localhost:9200/indices'
            curl -H "Content-Type: application/x-ndjson" -XPOST "localhost:9200/cs/_bulk" --data-binary @index-${{ github.run_number }}.json
            curl -H "Content-Type: application/x-ndjson" -XPOST "localhost:9200/en/_bulk" --data-binary @index-en-${{ github.run_number }}.json
            curl http://localhost:9200/_cat/indices?v
            rm index-${{ github.run_number }}.json
            rm index-en-${{ github.run_number }}.json
