name: deploy to production

on:
  workflow_dispatch:
#  push:
#    branches:
#      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.72.0"
          extended: true

      - name: Build
        run: hugo

      - name: Deploy via rsync
        uses: AEnterprise/rsync-deploy@v1.0
        env:
          DEPLOY_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          ARGS: "-avzr --delete --exclude 'uploads-import'"
          SERVER_PORT: ${{ secrets.SSH_PORT }}
          FOLDER: "./public/"
          SERVER_IP: ${{ secrets.SSH_HOSTNAME }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          SERVER_DESTINATION: /home/ochrance/public_html
