name: scp deploy

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8-18/2 * * 1-5"
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.81.0"
          extended: true

      - name: Build
        run: hugo

      - name: Compress build
        run: tar -zcf build-${{ github.run_number }}.tar.gz ./public

      - name: Publish
        uses: nogsantos/scp-deploy@master
        with:
          src: ./build-${{ github.run_number }}.tar.gz
          host: ${{ secrets.SSH_HOSTNAME }}
          remote: /home/ochrance/public_html
          port: ${{ secrets.SSH_PORT }}
          user: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Unpack tar into place
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd /home/ochrance/public_html
            echo ${{ github.run_number }} > GHRN.txt
            mkdir www-${{ github.run_number }}
            tar -xf build-${{ github.run_number }}.tar.gz -C ./www-${{ github.run_number }} --strip-components=2
            if [[ $(<GHRN.txt) > ${{ github.run_number }} ]]; then
              echo "Newer Github workflow detected. Aborting directory overwrite."
              rm -rf www-${{ github.run_number }}
            else
              mv www-prod www-old
              mv www-${{ github.run_number }} www-prod
              rm aktualne
              rm alert
              rm apple-touch-icon.png
              rm cs
              rm dokument
              rm elastic.json
              rm en
              rm err
              rm eso
              rm favicon-16x16.png
              rm favicon-32x32.png
              rm favicon.ico
              rm fonts
              rm hledat
              rm humans.txt
              rm images
              rm index.xml
              rm index.html
              rm info
              rm info106
              rm kontakt
              rm kontrola
              rm letaky
              rm manual
              rm o-nas
              rm organizacni-rad
              rm podejte-stiznost
              rm potrebuji-pomoc
              rm pravidla-komunikace
              rm pristupnost
              rm projekty
              rm provoz
              rm pusobnost
              rm robots.txt
              rm scripts
              rm setreni
              rm sitemap.xml
              rm situace
              rm statut
              rm style
              rm umluva
              rm umluva-player
              rm vyrocni-zpravy-106
              rm vystupy
              rm vzdelavaci-akce
              rm vzor
              rm media
              rm .htaccess
              rm obcane-eu
              ln -s www-prod/obcane-eu obcane-eu
              ln -s www-prod/aktualne aktualne
              ln -s www-prod/alert alert
              ln -s www-prod/apple-touch-icon.png apple-touch-icon.png
              ln -s www-prod/cs cs
              ln -s www-prod/dokument dokument
              ln -s www-prod/elastic.json elastic.json
              ln -s www-prod/en en
              ln -s www-prod/err err
              ln -s www-prod/eso eso
              ln -s www-prod/favicon-16x16.png favicon-16x16.png
              ln -s www-prod/favicon-32x32.png favicon-32x32.png
              ln -s www-prod/favicon.ico favicon.ico
              ln -s www-prod/fonts fonts
              ln -s www-prod/hledat hledat
              ln -s www-prod/humans.txt humans.txt
              ln -s www-prod/images images
              ln -s www-prod/index.xml index.xml
              ln -s www-prod/index.html index.html
              ln -s www-prod/info info
              ln -s www-prod/info106 info106
              ln -s www-prod/kontakt kontakt
              ln -s www-prod/kontrola kontrola
              ln -s www-prod/letaky letaky
              ln -s www-prod/manual manual
              ln -s www-prod/media media
              ln -s www-prod/o-nas o-nas
              ln -s www-prod/organizacni-rad organizacni-rad
              ln -s www-prod/podejte-stiznost podejte-stiznost
              ln -s www-prod/potrebuji-pomoc potrebuji-pomoc
              ln -s www-prod/pravidla-komunikace pravidla-komunikace
              ln -s www-prod/pristupnost pristupnost
              ln -s www-prod/projekty projekty
              ln -s www-prod/provoz provoz
              ln -s www-prod/pusobnost pusobnost
              ln -s www-prod/robots.txt robots.txt
              ln -s www-prod/scripts scripts
              ln -s www-prod/setreni setreni
              ln -s www-prod/sitemap.xml sitemap.xml
              ln -s www-prod/situace situace
              ln -s www-prod/statut statut
              ln -s www-prod/style style
              ln -s www-prod/umluva umluva
              ln -s www-prod/umluva-player umluva-player
              ln -s www-prod/vyrocni-zpravy-106 vyrocni-zpravy-106
              ln -s www-prod/vystupy vystupy
              ln -s www-prod/vzdelavaci-akce vzdelavaci-akce
              ln -s www-prod/vzor vzor
              ln -s www-prod/.htaccess .htaccess
              rm -rf www-old
            fi
            rm build-${{ github.run_number }}.tar.gz
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Update search indices
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            wget -O index-${{ github.run_number }}.json http://www.ochrance.cz/elastic.json
            wget -O index-en-${{ github.run_number }}.json http://www.ochrance.cz/en/elastic.json
            curl -X DELETE 'http://localhost:9200/indices'
            curl -H "Content-Type: application/x-ndjson" -XPOST "localhost:9200/cs/_bulk" --data-binary @index-${{ github.run_number }}.json
            curl -H "Content-Type: application/x-ndjson" -XPOST "localhost:9200/en/_bulk" --data-binary @index-en-${{ github.run_number }}.json
            curl http://localhost:9200/_cat/indices?v
          host: ${{ secrets.ELASTICUSER_HOSTNAME }}
          username: ${{ secrets.ELASTICUSER_USERNAME }}
          privateKey: ${{ secrets.ELASTICUSER_PRIVATE_KEY }}
