name: Update preview

concurrency:
  group: preview
  cancel-in-progress: true

env:
  NAME: preview-${{ github.run_number }}
  DEST: /home/ochrance/public_html/_preview

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Upload')"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.125.1'
          extended: true

      - name: Remove docs
        run: |
          find . -iregex '.*\.\(doc\|jpg\|mp4\|odp\|odt\|pdf\|png\|pps\|ppt\|rtf\|xls\|zip\)x?' -type f -delete

      - name: Build
        run: hugo --config preview.toml

      - name: Compress build
        run: |
          tar -zcf ${{ env.NAME }}.tar.gz ./public
          ls -l ${{ env.NAME }}.tar.gz

      - name: Publish
        uses: nogsantos/scp-deploy@master
        with:
          src: ./${{ env.NAME }}.tar.gz
          remote: /home/ochrance/tmp
          host: ${{ secrets.SSH_HOSTNAME }}
          port: ${{ secrets.SSH_PORT }}
          user: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Unpack tar into place
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ochrance/tmp
            echo ${{ github.run_number }} > PREVIEW-RUN-NUMBER.txt
            mkdir -p ${{ env.NAME }}/src

            cd ${{ env.NAME }}
            tar -xf ../${{ env.NAME }}.tar.gz -C ./src --strip-components=2

            if [[ $(<PREVIEW-RUN-NUMBER.txt) > ${{ github.run_number }} ]]; then
              echo "Newer Github workflow detected. Aborting directory overwrite."
            else
              mv ${{ env.DEST }} old
              mv src ${{ env.DEST }}
            fi

            cd ..
            rm ${{ env.NAME }}.tar.gz
            rm -rf ${{ env.NAME }}
