name: Publish preview

concurrency:
  group: preview
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Upload')"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.107.0'
          extended: true

      - name: Remove docs
        run: |
          find . -name "*.pdf" -type f -delete
          find . -name "*.docx" -type f -delete
          find . -name "*.doc" -type f -delete
          find . -name "*.rtf" -type f -delete
          find . -name "*.zip" -type f -delete

      - name: Build
        run: hugo --config preview.toml

      - name: Compress build
        run: tar -zcf _preview-${{ github.run_number }}.tar.gz ./public

      - name: Publish
        uses: nogsantos/scp-deploy@master
        with:
          src: ./_preview-${{ github.run_number }}.tar.gz
          host: ${{ secrets.SSH_HOSTNAME }}
          remote: /home/ochrance/public_html
          port: ${{ secrets.SSH_PORT }}
          user: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Unpack tar into place
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd /home/ochrance/public_html
            echo ${{ github.run_number }} > PREVIEW-GHRN.txt
            mkdir _preview-${{ github.run_number }}
            tar -xf _preview-${{ github.run_number }}.tar.gz -C ./_preview-${{ github.run_number }} --strip-components=2
            if [[ $(<PREVIEW-GHRN.txt) > ${{ github.run_number }} ]]; then
              echo "Newer Github workflow detected. Aborting directory overwrite."
              rm -rf _preview-${{ github.run_number }}
            else
              mv _preview _preview-old
              mv _preview-${{ github.run_number }} _preview
              rm -rf _preview-old
            fi
            rm _preview-${{ github.run_number }}.tar.gz
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
