name: Recreate symlinks

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Recreate symlinks on host
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ochrance/public_html
            rm aktualne
            rm alert
            rm apple-touch-icon.png
            rm cs
            rm dokument
            rm elastic.json
            rm en
            rm err
            rm eso
            rm favicon-16x16.png
            rm favicon-32x32.png
            rm favicon.ico
            rm fonts
            rm hledat
            rm humans.txt
            rm images
            rm index.xml
            rm index.html
            rm vyzkumy-vse
            rm info
            rm info106
            rm kontakt
            rm pro-media
            rm kontrola
            rm letaky
            rm manual
            rm o-nas
            rm podejte-stiznost
            rm potrebuji-pomoc
            rm pristupnost
            rm projekty
            rm provoz
            rm pusobnost
            rm robots.txt
            rm scripts
            rm sitemap.xml
            rm situace
            rm style
            rm umluva
            rm umluva-player
            rm vystupy
            rm vzdelavaci-akce
            rm zpravodaj
            rm zpravodaj-vse
            rm vzor
            rm media
            rm srozumitelne
            rm nas-pribeh
            rm .htaccess
            ln -s www-prod/aktualne aktualne
            ln -s www-prod/alert alert
            ln -s www-prod/apple-touch-icon.png apple-touch-icon.png
            ln -s www-prod/cs cs
            ln -s www-prod/dokument dokument
            ln -s www-prod/elastic.json elastic.json
            ln -s www-prod/en en
            ln -s www-prod/err err
            ln -s www-prod/eso eso
            ln -s www-prod/favicon-16x16.png favicon-16x16.png
            ln -s www-prod/favicon-32x32.png favicon-32x32.png
            ln -s www-prod/favicon.ico favicon.ico
            ln -s www-prod/fonts fonts
            ln -s www-prod/hledat hledat
            ln -s www-prod/humans.txt humans.txt
            ln -s www-prod/images images
            ln -s www-prod/index.xml index.xml
            ln -s www-prod/index.html index.html
            ln -s www-prod/vyzkumy-vse vyzkumy-vse
            ln -s www-prod/info info
            ln -s www-prod/info106 info106
            ln -s www-prod/kontakt kontakt
            ln -s www-prod/pro-media pro-media
            ln -s www-prod/kontrola kontrola
            ln -s www-prod/letaky letaky
            ln -s www-prod/manual manual
            ln -s www-prod/media media
            ln -s www-prod/o-nas o-nas
            ln -s www-prod/podejte-stiznost podejte-stiznost
            ln -s www-prod/potrebuji-pomoc potrebuji-pomoc
            ln -s www-prod/pristupnost pristupnost
            ln -s www-prod/projekty projekty
            ln -s www-prod/provoz provoz
            ln -s www-prod/pusobnost pusobnost
            ln -s www-prod/robots.txt robots.txt
            ln -s www-prod/scripts scripts
            ln -s www-prod/sitemap.xml sitemap.xml
            ln -s www-prod/situace situace
            ln -s www-prod/style style
            ln -s www-prod/umluva umluva
            ln -s www-prod/umluva-player umluva-player
            ln -s www-prod/vystupy vystupy
            ln -s www-prod/vzdelavaci-akce vzdelavaci-akce
            ln -s www-prod/vzor vzor
            ln -s www-prod/srozumitelne srozumitelne
            ln -s www-prod/nas-pribeh nas-pribeh
            ln -s www-prod/zpravodaj zpravodaj
            ln -s www-prod/zpravodaj-vse zpravodaj-vse
            ln -s www-prod/.htaccess .htaccess
